Update script

diff --git a/.github/workflows/publish-package.yaml b/.github/workflows/publish-package.yaml
--- a/.github/workflows/publish-package.yaml
+++ b/.github/workflows/publish-package.yaml
@@ -22,7 +22,9 @@ jobs:
     steps:
       - name: Extract branch name
         id: extract_branch_name
-        run: echo "branch_name=${GITHUB_REF##*/}">> $GITHUB_OUTPUT
+        run: |
+          echo "branch_name=${GITHUB_REF##*/}">> $GITHUB_OUTPUT
+          echo "Branch name is ${{ steps.extract_branch_name.outputs.branch_name }}"
 
   print_version_to_publish:
     needs: [extract_branch_name]
@@ -44,14 +46,14 @@ jobs:
 
       - name: Check if version is valid for branch
         run: |
-            if [[ "${{ needs.extract_branch_name.outputs.branch_name }}" == "v1.1" && ! "${{ needs.print_version_to_publish.outputs.core_sdk_version_to_be_published }}" =~ ^v1\.1\..* ]]; then
-              echo "Error: Invalid version for branch v1.1"
-              exit 1
-              fi
-              if [[ "${{ needs.extract_branch_name.outputs.branch_name }}" == "main" && ! "${{ needs.print_version_to_publish.outputs.core_sdk_version_to_be_published }}" =~ ^v1\.2\..* ]]; then
-              echo "Error: Invalid version for branch main"
-              exit 1
-              fi
+          if [[ "${{ needs.extract_branch_name.outputs.branch_name }}" == "v1.1" && ! "${{ needs.print_version_to_publish.outputs.core_sdk_version_to_be_published }}" =~ ^v1\.1 ]]; then
+            echo "Error: Invalid version for branch v1.1"
+            exit 1
+            fi
+            if [[ "${{ needs.extract_branch_name.outputs.branch_name }}" == "main" && ! "${{ needs.print_version_to_publish.outputs.core_sdk_version_to_be_published }}" =~ ^v1\.2\]]; then
+            echo "Error: Invalid version for branch main"
+            exit 1
+            fi
 
   # Fetch the latest version from NPM
   fetch_latest_version:
@@ -64,8 +66,31 @@ jobs:
       - name: Get latest package version
         id: get_latest_version
         run: |
-          CORE_SDK_LATEST_VERSION=$(npm view @story-protocol/core-sdk version --silent)
-          REACT_SDK_LATEST_VERSION=$(npm view @story-protocol/react-sdk version --silent || true)
+          get_latest_version() {
+            package_name=$1
+            branch_name=$2
+            if [ ${{ needs.extract_branch_name.outputs.branch_name }} = "main" ]; then
+              version_pattern ="v1.2"
+            else
+              version_pattern="v1.1"
+            fi
+            echo "Version is $VERSION"
+            versions=$(npm view $package_name versions --silent)
+            if [ -z "$versions" ]; then
+              echo "Not_Published"
+              return
+            fi
+            versions=$(echo $versions | tr -d '[],"')
+            latest_version=$(echo $versions | tr " " "\n" | grep -E "^$version_pattern" | sort -V | tail -n 1)
+            echo "Latest version of $package_name on NPMJS is $latest_version"
+            if [ -z "$latest_version" ]; then
+              echo "Not_Published"
+            else
+              echo $latest_version
+            fi
+          }
+          CORE_SDK_LATEST_VERSION=$(get_latest_version "@story-protocol/core-sdk" )
+          REACT_SDK_LATEST_VERSION=$(get_latest_version "@story-protocol/react-sdk")
           if [ -z "$REACT_SDK_LATEST_VERSION" ]; then
             echo "@story-protocol/react-sdk package not found on NPMJS"
             REACT_SDK_LATEST_VERSION="Not_Published"
