Update script

diff --git a/.github/workflows/publish-package.yaml b/.github/workflows/publish-package.yaml
--- a/.github/workflows/publish-package.yaml
+++ b/.github/workflows/publish-package.yaml
@@ -41,10 +41,10 @@ jobs:
         id: extract_branch_name
         run: |
           if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
-          echo "BRANCH_NAME=${GITHUB_REF##*/}">> $GITHUB_OUTPUT
+          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
           else
           branch_name=${GITHUB_HEAD_REF}
-          echo "BRANCH_NAME=${GITHUB_HEAD_REF}>> $GITHUB_OUTPUT
+          echo "BRANCH_NAME=${GITHUB_HEAD_REF} >> $GITHUB_OUTPUT
           fi
           echo "Branch name is '${BRANCH_NAME}'"
   # Fetch the latest version from NPM
@@ -68,6 +68,36 @@ jobs:
           echo "CORE_SDK_LATEST_VERSION=$CORE_SDK_LATEST_VERSION" >> $GITHUB_OUTPUT
           echo "Latest version of @story-protocol/react-sdk on NPMJS is $REACT_SDK_LATEST_VERSION"
           echo "REACT_SDK_LATEST_VERSION=$REACT_SDK_LATEST_VERSION" >> $GITHUB_OUTPUT
+
+  check_if_version_is_valid_for_branch:
+    needs: [print_version_to_publish]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if version is valid for branch
+      run: |
+          BRANCH_NAME="${{ needs.extract_branch_name.outputs.branch_name }}"
+          SDK_VERSION="${{ needs.print_version_to_publish.outputs.core_sdk_version_to_be_published }}"
+          REACT_SDK_VERSION="${{ needs.print_version_to_publish.outputs.react_sdk_version_to_be_published }}"
+          if [[ "$BRANCH_NAME" == "v1.1" ]]; then
+            if ! [[ "$SDK_VERSION" =~ ^v1\.1 ]]; then
+              echo "Error: Invalid version '$SDK_VERSION' for branch 'v1.1'"
+            exit 1
+            fi
+            if ! [[ "$REACT_SDK_VERSION" =~ ^v1\.1 ]]; then
+              echo "Error: Invalid version '$REACT_SDK_VERSION' for branch 'v1.1'"
+              exit 1
+              fi 
+          else
+            if ! [[ "$SDK_VERSION" =~ ^v1\.2 ]]; then
+            echo "Error: Invalid version '$SDK_VERSION' for branch 'main'"
+            exit 1
+            fi
+            if ! [[ "$REACT_SDK_VERSION" =~ ^v1\.2 ]]; then
+            echo "Error: Invalid version '$REACT_SDK_VERSION' for branch 'main'"
+            exit 1
+            fi
+          fi            
+
   # Fail the PR if the version to be published is the same as the latest version on NPM
   fail_if_version_is_same:
     needs: [print_version_to_publish, fetch_latest_version]
