Update script

diff --git a/.github/workflows/publish-package.yaml b/.github/workflows/publish-package.yaml
--- a/.github/workflows/publish-package.yaml
+++ b/.github/workflows/publish-package.yaml
@@ -29,7 +29,7 @@ jobs:
           branch_name=${GITHUB_HEAD_REF}
           echo "BRANCH_NAME=${GITHUB_HEAD_REF}>> $GITHUB_OUTPUT
           fi
-          echo "Branch name is ${{ steps.extract_branch_name.outputs.branch_name }}"
+          echo "Branch name is '${BRANCH_NAME}'"
 
   print_version_to_publish:
     needs: [extract_branch_name]
@@ -58,15 +58,24 @@ jobs:
         BRANCH_NAME="${{ needs.extract_branch_name.outputs.branch_name }}"
         SDK_VERSION="${{ needs.print_version_to_publish.outputs.core_sdk_version_to_be_published }}"
         REACT_SDK_VERSION="${{ needs.print_version_to_publish.outputs.react_sdk_version_to_be_published }}"
-        if [[ "$BRANCH_NAME" == "v1.1" && ! "$SDK_VERSION" =~ ^v1\.1 ]]; then
-          echo "Error: Invalid version "$SDK_VERSION" for branch v1.1, only can publish v1.1.x versions"
-          exit 1
-        fi
-
-        if [[ "$BRANCH_NAME" == "main" && ! "$SDK_VERSION" =~ ^v1\.2 ]]; then
-          echo "Error: Invalid version "$SDK_VERSION" for branch main, only can publish v1.2.x versions"
-          exit 1
-        fi
+        if [[ "$BRANCH_NAME" == "v1.1" ]]; then
+            if ! [[ "$SDK_VERSION" =~ ^v1\.1 ]]; then
+              echo "Error: Invalid version '$SDK_VERSION' for branch 'v1.1'"
+              exit 1
+            fi
+            if ! [[ "$REACT_SDK_VERSION" =~ ^v1\.1 ]]; then
+            echo "Error: Invalid version '$REACT_SDK_VERSION' for branch 'v1.1'"
+            exit 1
+          fi 
+        else
+            if ! [[ "$SDK_VERSION" =~ ^v1\.2 ]]; then
+              echo "Error: Invalid version '$SDK_VERSION' for branch 'main'"
+              exit 1
+            fi
+            if ! [[ "$REACT_SDK_VERSION" =~ ^v1\.2 ]]; then
+              echo "Error: Invalid version '$REACT_SDK_VERSION' for branch 'main'"
+              exit 1
+            fi
 
   # Fetch the latest version from NPM
   fetch_latest_version:
